### ISSUE TITLE
白天打光之女皇，界面发光的什么都看不见。

### ISSUE THREAD

**Issue by hunbei** [InfernumTeam/InfernumModePublic#142]
打白天模式的光之女皇，boss放技能时，屏幕亮的刺眼，啥都看不见
![图片](https://github.com/InfernumTeam/InfernumModePublic/assets/52339833/e47390c7-fae2-46b3-ab62-cf3b9fdfc620)

**Comment by hunbei** [comment]
我确认了，只有开启地狱mod的时候才会这样，关了mod就正常

**Comment by toasty599** [comment]
English?

**Comment by Godslayer40000** [comment]
When playing the Queen of Light in day mode, when the boss uses skills, the screen is so bright that you can't see anything.

I confirmed, it only happens when the hell mod is turned on, and it works normally when the mod is turned off. 

@toasty599 here you go dude, fully translated.  still I can translate but i cant exactly post his logs.

**Comment by toasty599** [comment]
Join the discord, and make a bug report there; in english.
